# Generated by Django 5.0.3 on 2024-08-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='product_name',
            new_name='Service_name',
        ),
    ]
