# Generated by Django 5.0.3 on 2024-08-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_contactquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactQuery',
        ),
    ]
