# Generated by Django 5.0.3 on 2024-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_delete_contactquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodigester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='biodigester_images/')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plumbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plumbing_images/')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='solar_installation_images/')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='water_treatment_images/')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
